parameters:
    podcast.upload_path: '%kernel.project_dir%/uploads/podcasts'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    Domain\Podcast\Repository\PodcastEpisodeRepositoryInterface: '@Infrastructure\Podcast\Doctrine\Repository\PodcastEpisodeRepository'
    Domain\Podcast\Repository\PodcastCollectionRepositoryInterface: '@Infrastructure\Podcast\Doctrine\Repository\PodcastCollectionRepository'
